image: node:latest

variables:
  POSTMAN_COLLECTION: https://api.getpostman.com/collections/b390fc03-0fdf-476e-beeb-7d3ef6b4eb02?apikey=$POSTMAN_API_KEY
  POSTMAN_ENVIRONMENT: https://api.getpostman.com/environments/db0ff19a-4aab-4f11-bc3d-5da6967bcff5?apikey=$POSTMAN_API_KEY

stages:
  - development
  - production
  - test

development:
  stage: development
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_DEVELOPMENT --api-key=$HEROKU_API_KEY
  only:
    - development

production:
  stage: production
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  only:
    - master

postman_tests:
  stage: test
  image:
    name: postman/newman_alpine33
    entrypoint: ['']
  script:
    - newman --version
    - newman run ${POSTMAN_COLLECTION} -e ${POSTMAN_ENVIRONMENT}